image: rustlang/rust:nightly
pipelines:
  default:
    - step:
        caches:
          - cargo
          - rust-target
        script:
          - echo "Build project"                    ; cargo build --release
  branches:
    dev:
      - step:
          caches:
            - cargo
            - rust-target
          script:
            - echo "Build project"                    ; cargo build --release
definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target
